// frontend/src/routes/Header.svelte
<header>
  <nav>
    <svg viewBox="0 0 2 3" aria-hidden="true">
      <path d="M0,0 L1,2 C1.5,3 1.5,3 2,3 L2,0 Z" />
    </svg>
    <ul>
      <li>
        <a
          href="https://www.sciencedirect.com/science/article/pii/S1053811920308326"
          >Publication</a
        >
      </li>
      <li>•</li>
      <li>
        <div style="display: flex; align-items: center;">
          <a href="https://github.com/TingsterX/alignment_macaque-human"
            >Data Repository</a
          >
        </div>
      </li>
      <li>•</li>
      <li>
        <div style="display: flex; align-items: center;">
          <a href="https://github.com/cmi-dair/cross-species-mapper"
            >Code Repository</a
          >
        </div>
      </li>
    </ul>
    <svg viewBox="0 0 2 3" aria-hidden="true">
      <path d="M0,0 L0,3 C0.5,3 0.5,3 1,2 L2,0 Z" />
    </svg>
  </nav>
  <vertical-spacing />
</header>

<style>
  header {
    display: flex;
    justify-content: center;
  }

  nav {
    display: flex;
    justify-content: center;
    position: relative;
    top: 0;
    left: 0;
    right: 0;
    z-index: 1;
    --background: rgba(255, 255, 255, 0.7);
  }

  svg {
    width: 2em;
    height: 3em;
    display: block;
  }

  path {
    fill: var(--background);
  }

  ul {
    position: relative;
    padding: 0;
    margin: 0;
    height: 3em;
    display: flex;
    justify-content: center;
    align-items: center;
    list-style: none;
    background: var(--background);
    background-size: contain;
    gap: 0.5rem;
  }

  li {
    position: relative;
    height: 100%;
    display: flex;
    align-items: center;
  }

  nav a {
    display: flex;
    height: 100%;
    align-items: center;
    padding: 0 0.5rem;
    color: var(--color-text);
    font-weight: 700;
    font-size: 0.8rem;
    text-transform: uppercase;
    letter-spacing: 0.1em;
    text-decoration: none;
    transition: color 0.2s linear;
  }

  a:hover {
    color: rgb(var(--color-theme-1));
  }

  vertical-spacing {
    height: 30px;
  }

  /* Media queries */
  @media only screen and (max-width: 600px) {
    nav a {
      font-size: 0.5em;
    }
  }
</style>

// frontend/src/components/Header.tsx
// @ts-expect-error because react not used.
import React from 'react'
import { Navbar, Nav } from 'react-bootstrap'
import { FaBookOpen, FaGithub } from 'react-icons/fa6'

const Header = (): JSX.Element => {
  return (
    <Navbar bg='light' expand='lg' fixed='top'>
      <Navbar.Brand style={{ marginLeft: '1rem' }}>Cross Species Mapper</Navbar.Brand>
      <Navbar.Toggle aria-controls='basic-navbar-nav' />
      <Navbar.Collapse id='basic-navbar-nav' className='justify-content-end'>
        <Nav className='mr-auto'>
          <Nav.Link
            href='https://www.sciencedirect.com/science/article/pii/S1053811920308326'
            className='d-flex align-items-center'
          >
            <FaBookOpen size={20} style={{ margin: '0 0.4rem 0 0.2rem' }} />
            Publication
          </Nav.Link>
          <Nav.Link
            href='https://github.com/cmi-dair/cross-species-mapper'
            className='d-flex align-items-center'
          >
            <FaGithub size={20} style={{ margin: '0 0.2rem 0 0.2rem' }} />
            Webapp
          </Nav.Link>
          <Nav.Link
            href='https://github.com/TingsterX/alignment_macaque-human'
            className='d-flex align-items-center'
          >
            <FaGithub size={20} style={{ margin: '0 0.2rem 0rem 0.2rem' }} />
            Data
          </Nav.Link>
        </Nav>
        <div style={{ marginRight: 5 }}>
          &copy; {new Date().getFullYear()} Child Mind Institute
        </div>
      </Navbar.Collapse>
    </Navbar>
  )
}

export default Header
