// frontend/src/routes/Introduction.svelte
<p>
  Welcome to our web application focusing on cross-species brain similarity!
  Gain valuable insights into the intriguing parallels between human and macaque
  brains. Designed for scientists, students, and curious minds alike, our
  user-friendly interface enables effortless navigation through the realm of
  cross-species brain similarity. Want a more detailed in-depth explanation of
  this project? Take a look at the links at the top to learn more!
</p>

<p>
  To rotate the brain, click and drag on the brain. To see data for a particular
  region, double click on the region.
</p>

// frontend/src/components/Introduction.tsx
// @ts-expect-error because React is a necessary unused import
import React from 'react'

export default function Introduction (): JSX.Element {
  return (
    <div>
      <p>
        Welcome to our web application focusing on cross-species brain
        similarity! Gain valuable insights into the intriguing parallels between
        human and macaque brains. Designed for scientists, students, and curious
        minds alike, our user-friendly interface enables effortless navigation
        through the realm of cross-species brain similarity. Want a more
        detailed in-depth explanation of this project? Take a look at the links
        at the top to learn more!
      </p>
    </div>
  )
}
